export interface AppConfig {
  VITE_API_URL: string;
  VITE_OIDC_ISSUER: string;
  VITE_OIDC_CLIENT_ID: string;
  // Optional audience to request in the access token (sent as an extraQueryParam).
  VITE_OIDC_JWT_AUD?: string;
  // Optional name of the query parameter used to request audience. Defaults to 'audience'.
  VITE_OIDC_JWT_AUD_PARAM?: string;
}

let config: AppConfig | null = null;

function isSubstituted(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0 && !value.startsWith('$');
}

/**
 * Loads application configuration from /config.json at runtime.
 * In Docker, config.json is generated by docker-entrypoint.sh via envsubst.
 * Falls back to Vite build-time env vars during local development.
 */
export async function loadConfig(): Promise<AppConfig> {
  if (config) return config;

  try {
    const response = await fetch('/config.json');
    if (response.ok) {
      const runtimeConfig = await response.json();
      if (
        isSubstituted(runtimeConfig.VITE_API_URL) &&
        isSubstituted(runtimeConfig.VITE_OIDC_ISSUER) &&
        isSubstituted(runtimeConfig.VITE_OIDC_CLIENT_ID)
      ) {
        config = runtimeConfig as AppConfig;
        console.info('Runtime configuration loaded successfully');
      }
    }
  } catch (error) {
    if (import.meta.env.PROD) {
      console.error('Failed to load runtime config, falling back to build-time env', error);
    }
  }

  if (!config) {
    config = {
      VITE_API_URL: import.meta.env.VITE_API_URL ?? 'http://localhost:8080',
      VITE_OIDC_ISSUER: import.meta.env.VITE_OIDC_ISSUER ?? '',
      VITE_OIDC_CLIENT_ID: import.meta.env.VITE_OIDC_CLIENT_ID ?? '',
      VITE_OIDC_JWT_AUD: import.meta.env.VITE_OIDC_JWT_AUD ?? undefined,
      VITE_OIDC_JWT_AUD_PARAM: import.meta.env.VITE_OIDC_JWT_AUD_PARAM ?? undefined,
    };
  }

  return config;
}

/**
 * Synchronously returns the already loaded configuration.
 * Must be called after loadConfig() has completed.
 */
export function getConfig(): AppConfig {
  if (!config) {
    return {
      VITE_API_URL: import.meta.env.VITE_API_URL ?? 'http://localhost:8080',
      VITE_OIDC_ISSUER: import.meta.env.VITE_OIDC_ISSUER ?? '',
      VITE_OIDC_CLIENT_ID: import.meta.env.VITE_OIDC_CLIENT_ID ?? '',
      VITE_OIDC_JWT_AUD: import.meta.env.VITE_OIDC_JWT_AUD ?? undefined,
      VITE_OIDC_JWT_AUD_PARAM: import.meta.env.VITE_OIDC_JWT_AUD_PARAM ?? undefined,
    };
  }
  return config;
}
