name = "budget-buddy-web-app"
pages_build_output_dir = "./dist"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_API_URL = "https://budgetbuddy.glebremniov.keenetic.link"
VITE_OIDC_ISSUER = "https://budget-buddy-zk5ltr.eu1.zitadel.cloud"
VITE_OIDC_CLIENT_ID = "369170042299971005"
VITE_OIDC_SCOPES = "urn:zitadel:iam:org:project:id:budget-buddy-api:aud"
VITE_OIDC_USER_MANAGEMENT_URL = "https://budget-buddy-zk5ltr.eu1.zitadel.cloud/ui/console/users/me"

[observability]
enabled = true
